name: generate pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        run: |
          mkdir output
          sudo apt-get update
          sudo apt-get install pandoc
          sudo apt install texlive texlive-latex-extra texlive-latex-recommended texlive-xetex pandoc
          pandoc --latex-engine=xelatex --output=output/SpinalHDL中文手册.pdf SpinalHDL_Chinese_Doc.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output