name: generate pdf

on: push

jobs:
  dependencies:
    name: Build dependencies
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Create global variables
        id: version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

  release:
    name: "Create Github tag/pre-release"
    runs-on: ubuntu-latest
    needs: dependencies
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Github pre-release (${{ needs.dependencies.outputs.version }})
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-${{ needs.dependencies.outputs.version }}
          release_name: Version ${{ github.run_number }} (${{ needs.dependencies.outputs.version }})
          draft: false
          prerelease: true

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: "setup python"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: "install dependencies"
      run: |
        apt-get update -y && apt-get install -y git
        pip install -r requirements.txt
    - uses: ammaraskar/sphinx-problem-matcher@master
    - name: "check links"
      run: |
        cd Sphinx
        make linkcheck
    - name: "Test doc building"
      run: |
        cd Sphinx
        make html
        zip -r _build/SpinalHDL_Chinese_Doc_html.zip _build/html/
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: Sphinx/_build
    - name: Upload release assets html
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: Sphinx/_build/SpinalHDL_Chinese_Doc_html.zip
        asset_name: SpinalHDL_Chinese_Doc_html.zip
        asset_content_type: application/zip
